spring:
  application:
    name: 青柠招聘
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 40MB

  datasource:
    url: jdbc:mysql://localhost:3306/hangaituangou
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

file:
  upload:
    resume-path: D:/青柠招聘/resume/

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 添加以下配置以帮助诊断
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8088

logging:
  level:
    org:
      springframework: error